<?php

return [
    'Acme', 'Ada', 'Addison', 'Adrian', 'Afton', 'Ahmeek', 'Akron', 'Alanson', 'Alba', 'Albion',
    'Alden', 'Alger', 'Algonac', 'Allegan', 'Allen', 'Allen Park', 'Allendale', 'Allouez', 'Alma',
    'Almont', 'Alpena', 'Alpha', 'Alto', 'Amasa', 'Anchorville', 'Ann Arbor', 'Applegate', 'Arcadia',
    'Argyle', 'Armada', 'Arnheim', 'Ashley', 'Athens', 'Atlanta', 'Atlantic Mine', 'Atlas', 'Attica',
    'Au Gres', 'Au Train', 'Auburn', 'Auburn Hills', 'Augusta', 'Avoca', 'Azalia', 'Bad Axe',
    'Bailey', 'Baldwin', 'Bancroft', 'Bangor', 'Bannister', 'Baraga', 'Barbeau', 'Bark River',
    'Baroda', 'Barryton', 'Barton City', 'Base Line', 'Batavia', 'Bates', 'Bath', 'Battle Creek',
    'Bay City', 'Bay Port', 'Bayside', 'Bear Lake', 'Beaver Island', 'Beaverton', 'Bedford',
    'Belding', 'Bellaire', 'Belleville', 'Bellevue', 'Belmont', 'Benton Harbor', 'Benzonia',
    'Bergland', 'Berkley', 'Berrien Center', 'Berrien Springs', 'Bessemer', 'Beulah', 'Big Bay',
    'Big Rapids', 'Birch Run', 'Birmingham', 'Biteley', 'Black River', 'Blanchard', 'Blissfield',
    'Bloomfield Hills', 'Bloomingdale', 'Boon', 'Boyne City', 'Boyne Falls', 'Bradley', 'Branch',
    'Brant', 'Breckenridge', 'Breedsville', 'Brethren', 'Bridgeport', 'Bridgewater', 'Bridgman',
    'Brighton', 'Brimley', 'Britton', 'Brohman', 'Bronson', 'Brooklyn', 'Brown City', 'Bruce Crossing',
    'Brunswick', 'Brutus', 'Buchanan', 'Buckley', 'Burlington', 'Burnips', 'Burr Oak', 'Burt',
    'Burt Lake', 'Burton', 'Byron', 'Byron Center', 'Cadillac', 'Caledonia', 'Calumet', 'Camden',
    'Cannonsburg', 'Canton', 'Capac', 'Carleton', 'Carlstadt', 'Carney', 'Caro', 'Carp Lake',
    'Carrollton', 'Carson City', 'Carsonville', 'Casco', 'Caseville', 'Casnovia', 'Caspian',
    'Cass City', 'Cassopolis', 'Cedar', 'Cedar River', 'Cedar Springs', 'Cedarville', 'Cement City',
    'Center Line', 'Central Lake', 'Centreville', 'Ceresco', 'Champion', 'Channing', 'Charlevoix',
    'Charlotte', 'Chase', 'Chassell', 'Chatham', 'Cheboygan', 'Chelsea', 'Chesaning', 'Chippewa Lake',
    'Clare', 'Clarklake', 'Clarkston', 'Clarksville', 'Clawson', 'Clayton', 'Clifford', 'Climax',
    'Clinton', 'Clinton Township', 'Clio', 'Cloverdale', 'Cohoctah', 'Coldwater', 'Coleman',
    'Coloma', 'Colon', 'Columbiaville', 'Comins', 'Commerce Township', 'Comstock', 'Comstock Park',
    'Concord', 'Conklin', 'Constantine', 'Conway', 'Cooks', 'Coopersville', 'Copemish', 'Copper City',
    'Copper Harbor', 'Coral', 'Cornell', 'Corunna', 'Covert', 'Covington', 'Cross Village', 'Croswell',
    'Crystal', 'Crystal Falls', 'Curran', 'Curtis', 'Custer', 'Dafter', 'Daggett', 'Dansville',
    'Davisburg', 'Davison', 'Dayton', 'De Tour Village', 'Dearborn', 'Dearborn Heights', 'Decatur',
    'Decker', 'Deckerville', 'Deerfield', 'Deerton', 'Deford', 'Delton', 'Detroit', 'DeWitt',
    'Dexter', 'Dimondale', 'Dodgeville', 'Dollar Bay', 'Dorr', 'Douglas', 'Dowagiac', 'Dowling',
    'Drayton Plains', 'Drummond Island', 'Dryden', 'Dundee', 'Durand', 'Eagle', 'Eagle Harbor',
    'Eagle River', 'East China', 'East Jordan', 'East Lansing', 'East Leroy', 'East Pointe', 'East Tawas',
    'Eastlake', 'Eastpointe', 'Eaton Rapids', 'Eau Claire', 'Eben Junction', 'Eckerman', 'Ecorse',
    'Edenville', 'Edmore', 'Edwardsburg', 'Elberta', 'Elk Rapids', 'Elkton', 'Ellsworth', 'Elm Hall',
    'Elmira', 'Elsie', 'Elwell', 'Emmett', 'Empire', 'Engadine', 'Erie', 'Escanaba', 'Essexville',
    'Eureka', 'Evart', 'Ewen', 'Fair Haven', 'Fairgrove', 'Fairview', 'Falmouth', 'Farmington',
    'Farmington Hills', 'Farwell', 'Fayette', 'Felch', 'Fennville', 'Fenton', 'Fenwick', 'Ferndale',
    'Ferrysburg', 'Fife Lake', 'Filer City', 'Fillmore', 'Flat Rock', 'Flint', 'Flushing', 'Fostoria',
    'Fountain', 'Fowler', 'Fowlerville', 'Frankenmuth', 'Frankfort', 'Franklin', 'Fraser', 'Frederic',
    'Freeland', 'Freeport', 'Free Soil', 'Fremont', 'Frontier', 'Fruitport', 'Fulton', 'Gaastra',
    'Gagetown', 'Gaines', 'Galesburg', 'Galien', 'Garden', 'Garden City', 'Gaylord', 'Genesee',
    'Germfask', 'Gilford', 'Gladstone', 'Gladwin', 'Glen Arbor', 'Glennie', 'Gobles', 'Goetzville',
    'Goodells', 'Good Hart', 'Goodland', 'Goodrich', 'Gould City', 'Gowen', 'Grand Blanc',
    'Grand Haven', 'Grand Ledge', 'Grand Marais', 'Grand Rapids', 'Grandville', 'Grant', 'Grass Lake',
    'Grawn', 'Greenbush', 'Greenland', 'Greenville', 'Gregory', 'Grosse Ile', 'Grosse Pointe',
    'Gulliver', 'Gwinn', 'Hadley', 'Hagar Shores', 'Hale', 'Hamburg', 'Hamilton', 'Hamtramck',
    'Hancock', 'Hanover', 'Harbert', 'Harbor Beach', 'Harbor Springs', 'Hardwood', 'Harper Woods',
    'Harrietta', 'Harris', 'Harrison', 'Harrison Township', 'Harrisville', 'Harsens Island',
    'Hart', 'Hartford', 'Hartland', 'Haslett', 'Hastings', 'Hawks', 'Hazel Park', 'Hemlock',
    'Henderson', 'Hermansville', 'Herron', 'Hersey', 'Hesperia', 'Hessel', 'Hickory Corners',
    'Higgins Lake', 'Highland', 'Highland Park', 'Hillman', 'Hillsdale', 'Holland', 'Holly',
    'Holt', 'Holton', 'Homer', 'Honor', 'Hope', 'Hopkins', 'Horton', 'Houghton', 'Houghton Lake',
    'Howard City', 'Howell', 'Hoxeyville', 'Hubbard Lake', 'Hubbardston', 'Hubbell', 'Hudson',
    'Hudsonville', 'Hulbert', 'Huntington Woods', 'Ida', 'Idlewild', 'Imlay City', 'Indian River',
    'Ingalls', 'Inkster', 'Interlochen', 'Ionia', 'Iron Mountain', 'Iron River', 'Irons', 'Ironwood',
    'Ishpeming', 'Ithaca', 'Jackson', 'Jamestown', 'Jasper', 'Jeddo', 'Jenison', 'Jerome',
    'Johannesburg', 'Jones', 'Jonesville', 'Kalamazoo', 'Kaleva', 'Kalkaska', 'Karlin', 'Kawkawlin',
    'Kearsarge', 'Keego Harbor', 'Kendall', 'Kent City', 'Kentwood', 'Kewadin', 'Keweenaw Bay',
    'Kincheloe', 'Kinde', 'Kingsford', 'Kingsley', 'Kingston', 'Kinross', 'Lachine', 'Lacota',
    'Laingsburg', 'Lake', 'Lake Ann', 'Lake City', 'Lake George', 'Lake Leelanau', 'Lake Linden',
    'Lake Odessa', 'Lake Orion', 'Lakeland', 'Lakeside', 'Lakeview', 'Lakeville', 'Lambertville',
    'Lamont', 'L\'Anse', 'Lansing', 'Lapeer', 'La Salle', 'Laurium', 'Lawrence', 'Lawton',
    'Leland', 'Lennon', 'Leonard', 'Leonidas', 'Le Roy', 'Leslie', 'Levering', 'Lewiston',
    'Lexington', 'Limestone', 'Lincoln', 'Lincoln Park', 'Linden', 'Linwood', 'Litchfield',
    'Little Lake', 'Livonia', 'Long Lake', 'Loretto', 'Lowell', 'Ludington', 'Luna Pier',
    'Lupton', 'Luther', 'Luzerne', 'Lyon Mountain', 'Macatawa', 'Mackinac Island', 'Mackinaw City',
    'Macomb', 'Macon', 'Madison Heights', 'Mancelona', 'Manchester', 'Manistee', 'Manistique',
    'Manitou Beach', 'Manton', 'Maple City', 'Maple Rapids', 'Marcellus', 'Marenisco', 'Marine City',
    'Marion', 'Marlette', 'Marne', 'Marquette', 'Marshall', 'Martin', 'Marysville', 'Mason',
    'Mass City', 'Mattawan', 'Maybee', 'Mayfield', 'Mayville', 'McBain', 'McBrides', 'McMillan',
    'Mears', 'Mecosta', 'Melina', 'Melvindale', 'Memphis', 'Mendon', 'Menominee', 'Merrill',
    'Merritt', 'Mesick', 'Metamora', 'Michigamme', 'Michigan Center', 'Middleton', 'Middleville',
    'Midland', 'Mikado', 'Milan', 'Milford', 'Millersburg', 'Millington', 'Minden City', 'Mio',
    'Mohawk', 'Moline', 'Monroe', 'Montague', 'Montgomery', 'Montrose', 'Moran', 'Morenci',
    'Morley', 'Morrice', 'Moscow', 'Mosherville', 'Mount Clemens', 'Mount Morris', 'Mount Pleasant',
    'Muir', 'Mullett Lake', 'Mulliken', 'Munger', 'Munising', 'Munith', 'Muskegon', 'Muskegon Heights',
    'Nadeau', 'Nahma', 'Napoleon', 'Nashville', 'National City', 'National Mine', 'Naubinway',
    'Nazareth', 'Negaunee', 'New Baltimore', 'New Boston', 'New Buffalo', 'New Era', 'New Haven',
    'New Hudson', 'New Lothrop', 'New Troy', 'Newaygo', 'Newberry', 'Newport', 'Niles', 'Nisula',
    'North Adams', 'North Branch', 'North Bradley', 'North Street', 'Northland', 'Northport',
    'Northville', 'Norton Shores', 'Norvell', 'Norway', 'Nottawa', 'Novi', 'Nunica', 'Oak Grove',
    'Oak Park', 'Oakland', 'Oakley', 'Oceola', 'Oden', 'Okemos', 'Old Mission', 'Olivet', 'Omena',
    'Omer', 'Onaway', 'Onekama', 'Onondaga', 'Onsted', 'Ontonagon', 'Orchard Lake', 'Orleans',
    'Ortonville', 'Oscoda', 'Oshtemo', 'Osseo', 'Ossineke', 'Otisville', 'Otsego', 'Ottawa Lake',
    'Otter Lake', 'Ovid', 'Owendale', 'Owosso', 'Oxford', 'Palisades Park', 'Palmer', 'Palms',
    'Palmyra', 'Palo', 'Paradise', 'Parchment', 'Paris', 'Parma', 'Paw Paw', 'Pearl Beach',
    'Peck', 'Pelkie', 'Pellston', 'Pentwater', 'Perkins', 'Perrinton', 'Perronville', 'Perry',
    'Petersburg', 'Petoskey', 'Pewamo', 'Pickford', 'Pierson', 'Pigeon', 'Pinckney', 'Pinconning',
    'Pittsford', 'Plainwell', 'Pleasant Ridge', 'Plymouth', 'Pointe Aux Barques', 'Pointe Aux Pins',
    'Pompeii', 'Pontiac', 'Port Austin', 'Port Hope', 'Port Huron', 'Port Sanilac', 'Portage',
    'Portland', 'Posen', 'Potterville', 'Powers', 'Prescott', 'Presque Isle', 'Prudenville',
    'Pullman', 'Quincy', 'Quinnesec', 'Ralph', 'Ramsay', 'Rapid City', 'Rapid River', 'Ravenna',
    'Reading', 'Redford', 'Reed City', 'Reese', 'Remus', 'Republic', 'Rhodes', 'Richland',
    'Richmond', 'Richville', 'Riga', 'River Rouge', 'Riverdale', 'Riverside', 'Riverview', 'Rives Junction',
    'Rochester', 'Rochester Hills', 'Rock', 'Rockford', 'Rockland', 'Rockwood', 'Rodney', 'Rogers City',
    'Rollin', 'Romeo', 'Romulus', 'Roscommon', 'Rose City', 'Rosebush', 'Roseville', 'Rothbury',
    'Royal Oak', 'Ruby', 'Rudyard', 'Ruth', 'Saginaw', 'Sagola', 'Saint Charles', 'Saint Clair',
    'Saint Clair Shores', 'Saint Helen', 'Saint Ignace', 'Saint James', 'Saint Johns', 'Saint Joseph',
    'Saint Louis', 'Salem', 'Saline', 'Samaria', 'Sand Creek', 'Sand Lake', 'Sandusky', 'Sanford',
    'Saranac', 'Saugatuck', 'Sault Sainte Marie', 'Sawyer', 'Schaffer', 'Schoolcraft', 'Scotts',
    'Scottville', 'Sears', 'Sebewaing', 'Selfridge', 'Seneca', 'Seney', 'Shaftsburg', 'Shelby',
    'Shelbyville', 'Shepherd', 'Sheridan', 'Sherman', 'Shingleton', 'Sidnaw', 'Sidney', 'Silverwood',
    'Six Lakes', 'Skandia', 'Skanee', 'Smyrna', 'Snover', 'Sodus', 'Somerset', 'Somerset Center',
    'South Boardman', 'South Branch', 'South Haven', 'South Lyon', 'South Rockwood', 'Southfield',
    'Southgate', 'Spalding', 'Sparta', 'Spring Arbor', 'Spring Lake', 'Springfield', 'Springport',
    'Spruce', 'Stalwart', 'Stambaugh', 'Standish', 'Stanton', 'Stanwood', 'Stephenson', 'Sterling',
    'Sterling Heights', 'Stevensville', 'Stockbridge', 'Stronach', 'Strongs', 'Sturgis', 'Sumner',
    'Sumpter', 'Sunfield', 'Suttons Bay', 'Swartz Creek', 'Sylvan Lake', 'Tawas City', 'Taylor',
    'Tecumseh', 'Tekonsha', 'Temperance', 'Thompsonville', 'Three Oaks', 'Three Rivers', 'Tipton',
    'Toivola', 'Topinabee', 'Tower', 'Traverse City', 'Trenary', 'Trenton', 'Trout Creek',
    'Trout Lake', 'Troy', 'Trufant', 'Turner', 'Tuscola', 'Tustin', 'Twining', 'Twin Lake',
    'Ubly', 'Union', 'Union City', 'Union Lake', 'Union Pier', 'Unionville', 'University Center',
    'Utica', 'Vandalia', 'Vanderbilt', 'Vassar', 'Vermontville', 'Vernon', 'Vestaburg', 'Vicksburg',
    'Vulcan', 'Wakefield', 'Waldron', 'Walhalla', 'Walker', 'Walkerville', 'Walled Lake', 'Walloon Lake',
    'Warren', 'Washington', 'Waterford', 'Waters', 'Watersmeet', 'Watervliet', 'Watrousville', 'Wayland',
    'Wayne', 'Webberville', 'Weidman', 'Wells', 'Wellston', 'Wequetonsing', 'West Bloomfield', 'West Branch',
    'West Olive', 'Westland', 'Weston', 'Westphalia', 'Wetmore', 'Wheeler', 'White Cloud', 'White Lake',
    'White Pigeon', 'White Pine', 'Whitehall', 'Whitmore Lake', 'Whittaker', 'Whittemore', 'Williamsburg',
    'Williamston', 'Willis', 'Wilson', 'Winn', 'Wixom', 'Wolverine', 'Woodland', 'Wyandotte',
    'Wyoming', 'Yale', 'Ypsilanti', 'Zeeland'
];
